apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: dev
  labels:
    app: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx
          image: damiano000/myapp:20250711
          ports:
            - containerPort: 80
