pipeline {
    agent any
    environment {
        TARGET_ENV = 'test'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Compilation ok!'
            }
        }
        stage('Deploy in production') {
            when {
                expression {
                    env.TARGET_ENV == 'prod'
                }
            }
            steps {
                echo 'Deploying to production environment!'
            }
        }
        stage('Deploy in test') {
            when {
                expression {
                    env.TARGET_ENV == 'test'
                }
            }

            steps {
                echo 'Deploy to test environment!'
            }
        }
    }
}
