pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo Hello > output.txt'
            }
        }
        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'output.txt', onlyIfSuccessful: true
            }
        }
    }
}
